### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by mikesoule** [spartantri/wafme#5]
Followed instructions in the README, output below. Is this a bug or user error on my part?

```bash
[root@localhost]$ python WAFme.py 
No GUI
Testing file access /root/wafme/apache_restart.sh
File /root/wafme/apache_restart.sh exists and permissions are ok
Testing file access /root/wafme/REQUEST-903.9003-CUSTOMAPP-EXCLUSION-RULES.conf
File /root/wafme/REQUEST-903.9003-CUSTOMAPP-EXCLUSION-RULES.conf exists and permissions are ok
Testing file access /root/wafme/audit.log
File /root/wafme/audit.log exists and permissions are ok
/root/wafme/Reference-Manual.html
Getting Variables
Starting rule id will be : 37183
Increases to rule id will be : 10
Press CTRL+C to finish tailing /root/wafme/audit.log and output the rules to /root/wafme/REQUEST-903.9003-CUSTOMAPP-EXCLUSION-RULES.conf
Traceback (most recent call last):
  File "WAFme.py", line 524, in <module>
    main()
  File "WAFme.py", line 520, in main
    t.follow()
  File "/root/wafme/tail.py", line 59, in follow
    self.callback(line)
  File "WAFme.py", line 111, in extractor
    uri=re.search('^\w+\s(\/[^\?\s]+)\??.*\sHTTP\/(?:(?:1|2)\.?(?:1|0)?)$', find_values('request_line', jsonlog)[0])
  File "WAFme.py", line 101, in find_values
    json.loads(json_repr, object_hook=_decode_dict)  # Return value ignored.
  File "/usr/lib64/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by spartantri** [comment]
Hi @mikesoule sorry for the delay, is the log file in json format?

**Comment by mikesoule** [comment]
@spartantri It was not in JSON format. I'll close this issue and re-open after I get a chance to try it out.
